# Generated by Django 5.2 on 2025-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
