# Generated by Django 5.2 on 2025-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smjer',
            name='predmeti',
            field=models.ManyToManyField(related_name='smjerovi', to='upis.predmet'),
        ),
    ]
