# Generated by Django 5.2 on 2025-04-19 08:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upis", "0002_smjer_predmeti"),
    ]

    operations = [
        migrations.AddField(
            model_name="prijave",
            name="datum_rođenja",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prijave",
            name="dokument",
            field=models.FileField(blank=True, null=True, upload_to="dokumenti/"),
        ),
        migrations.AddField(
            model_name="prijave",
            name="mjesto_rođenja",
            field=models.CharField(default=datetime.date(2000, 1, 1), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prijave",
            name="molba",
            field=models.FileField(blank=True, null=True, upload_to="molbe/"),
        ),
        migrations.AddField(
            model_name="prijave",
            name="ocjena_matura",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prijave",
            name="prosjek_ocjena",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prijave",
            name="završena_škola",
            field=models.CharField(default=datetime.date(2000, 1, 1), max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PredmetiSmjera",
        ),
    ]
