# Generated by Django 5.2 on 2025-04-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0004_korisnik_groups_korisnik_is_active_korisnik_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prijave',
            new_name='Prijava',
        ),
        migrations.AlterModelTable(
            name='smjer',
            table='smjerovi',
        ),
    ]
