# Generated by Django 5.2 on 2025-04-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0005_rename_prijave_prijava_alter_smjer_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smjer',
            old_name='slobodna_mjesta',
            new_name='slobodno',
        ),
    ]
