# Generated by Django 5.2 on 2025-04-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0002_alter_korisnik_password'),
        ('upis', '0006_rename_slobodna_mjesta_smjer_slobodno'),
    ]

    operations = [
    ]
