--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Ubuntu 17.4-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: korisnici; Type: TABLE; Schema: public; Owner: pguser
--

CREATE TABLE public.korisnici (
    id bigint NOT NULL,
    ime character varying(100) NOT NULL,
    prezime character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    password_hash character varying(255) NOT NULL,
    tip_korisnika character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_superuser boolean NOT NULL,
    last_login timestamp with time zone
);


ALTER TABLE public.korisnici OWNER TO pguser;

--
-- Name: korisnici_id_seq; Type: SEQUENCE; Schema: public; Owner: pguser
--

ALTER TABLE public.korisnici ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.korisnici_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: predmeti; Type: TABLE; Schema: public; Owner: pguser
--

CREATE TABLE public.predmeti (
    id bigint NOT NULL,
    naziv character varying(100) NOT NULL,
    opis character varying(200) NOT NULL,
    nositelj character varying(100) NOT NULL,
    ects integer NOT NULL
);


ALTER TABLE public.predmeti OWNER TO pguser;

--
-- Name: predmeti_id_seq; Type: SEQUENCE; Schema: public; Owner: pguser
--

ALTER TABLE public.predmeti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.predmeti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prijave; Type: TABLE; Schema: public; Owner: pguser
--

CREATE TABLE public.prijave (
    id bigint NOT NULL,
    korisnik_id bigint NOT NULL,
    smjer_id bigint NOT NULL,
    "datum_rođenja" date NOT NULL,
    dokument character varying(100),
    "mjesto_rođenja" character varying(100) NOT NULL,
    molba character varying(100),
    ocjena_matura integer,
    prosjek_ocjena double precision,
    "završena_škola" character varying(100) NOT NULL
);


ALTER TABLE public.prijave OWNER TO pguser;

--
-- Name: prijave_id_seq; Type: SEQUENCE; Schema: public; Owner: pguser
--

ALTER TABLE public.prijave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prijave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upisi; Type: TABLE; Schema: public; Owner: pguser
--

CREATE TABLE public.upisi (
    id bigint NOT NULL,
    vrijeme_odobrenja timestamp with time zone NOT NULL,
    objasnjenje_odobrenja text NOT NULL,
    student_id bigint NOT NULL,
    upisnik_id bigint NOT NULL
);


ALTER TABLE public.upisi OWNER TO pguser;

--
-- Name: upisi_id_seq; Type: SEQUENCE; Schema: public; Owner: pguser
--

ALTER TABLE public.upisi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upisi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: korisnici; Type: TABLE DATA; Schema: public; Owner: pguser
--

COPY public.korisnici (id, ime, prezime, email, password_hash, tip_korisnika, is_active, is_staff, is_superuser, last_login) FROM stdin;
11	test123	test123	test@123.com	pbkdf2_sha256$1000000$VeGGufR3poe3OWL5KvuUo2$4xyvYiXO0HzLJNPFNZP+opuEj/jklWVTElpm/mphqGg=	user	t	f	f	\N
13	pero	peroić	sdfvs@esef.csm	pbkdf2_sha256$1000000$20cklUHGrMdObe4sXkp8Es$liLuZd6jXK29cWCXF4dtIuzUvSdgPyo+iwV+UfJiJDs=	admin	t	t	t	\N
4	Toma	Milić2	tomo@gmail.com	pbkdf2_sha256$1000000$z36GS0GpOTl4uayXMgRfkW$ga0iRh1MTqGwM5XAwzYqpHESka5RGVCU14AP4opGNhY=	admin	t	t	t	\N
9	test	test	test@test.com	pbkdf2_sha256$1000000$skzaIqlabMDqBhnJWXsI9d$qsnGypahcJ4TPxemEtp+N7obelWXiz5mZUvuU1YT+OA=	user	t	f	f	2025-04-21 11:29:15.611305+00
7	Tomislav	Nazifović	tomislav.nazifovic@gmail.com	pbkdf2_sha256$1000000$skzaIqlabMDqBhnJWXsI9d$qsnGypahcJ4TPxemEtp+N7obelWXiz5mZUvuU1YT+OA=	admin	t	t	t	2025-04-21 11:31:19.526974+00
1	Ana	Marić	ana@gmail.com	pbkdf2_sha256$1000000$Q8IHFtyEzlF5ZZbjOWJvH8$YM5eVAuu5KUD7pa++irajEXlSSzvE6DRsoiYSZHcJz8=	user	t	f	f	\N
2	Pero	Ivić	pero@gmail.com	pbkdf2_sha256$1000000$H6rRCgogqlUtqb91NIMXPr$P0n/VdXpoYdoZGt2Bl0QDiLEYgBJL+I3kwOLSUReB7w=	user	t	f	f	\N
3	Marko	Anić	marko@gmail.com	pbkdf2_sha256$1000000$z36GS0GpOTl4uayXMgRfkW$ga0iRh1MTqGwM5XAwzYqpHESka5RGVCU14AP4opGNhY=	user	t	f	f	\N
\.


--
-- Data for Name: predmeti; Type: TABLE DATA; Schema: public; Owner: pguser
--

COPY public.predmeti (id, naziv, opis, nositelj, ects) FROM stdin;
1	Matematika 1	Uvodni semestar matematike	Jozić	20
2	Matematika 2	Napredni semestar matematike	Jozić	30
3	Programiranje 1	Uvod u programiranje	Buljat	15
4	Programiranje 2	Objektno orjentirano programiranje	Sokol	25
5	Tehničko crtanje	Osnove tehničkog crtanja	Milić	20
\.


--
-- Data for Name: prijave; Type: TABLE DATA; Schema: public; Owner: pguser
--

COPY public.prijave (id, korisnik_id, smjer_id, "datum_rođenja", dokument, "mjesto_rođenja", molba, ocjena_matura, prosjek_ocjena, "završena_škola") FROM stdin;
1	1	2	2000-01-01		Zagreb		5	4.5	MIOC
2	2	2	2000-01-01		Osijek		4	4.5	III Gim
3	2	3	2000-01-01		Osijek		4	4.5	III Gim
8	9	2	2025-04-16	dokumenti/Entrio-ulaznica-23058-57013058134501274827_w64cMYt.pdf	Osijek	molbe/Entrio-ulaznica-23058-57013058134501274827_jGsyuDT.pdf	3	3	III Gim
9	9	3	2025-04-16	dokumenti/Entrio-ulaznica-23058-57013058134501274827_Ap6wQ4Z.pdf	Osijek	molbe/Entrio-ulaznica-23058-57013058134501274827_Sr0Bfsm.pdf	3	3	III Gim
12	9	1	2025-04-17	dokumenti/Entrio-ulaznica-23058-57013058184330800753.pdf	Osijek	molbe/Entrio-ulaznica-23058-57013058184330800753.pdf	3	3	III Gim
\.


--
-- Data for Name: upisi; Type: TABLE DATA; Schema: public; Owner: pguser
--

COPY public.upisi (id, vrijeme_odobrenja, objasnjenje_odobrenja, student_id, upisnik_id) FROM stdin;
1	2025-04-19 00:00:00+00	Testno odobrenje	1	4
2	2025-04-19 00:00:00+00	Testno odobrenje	1	4
3	2025-04-19 09:21:22.154254+00	Testno odobrenje	1	4
4	2025-04-19 09:21:28.069674+00	Testno odobrenje	1	4
\.


--
-- Name: korisnici_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pguser
--

SELECT pg_catalog.setval('public.korisnici_id_seq', 13, true);


--
-- Name: predmeti_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pguser
--

SELECT pg_catalog.setval('public.predmeti_id_seq', 5, true);


--
-- Name: prijave_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pguser
--

SELECT pg_catalog.setval('public.prijave_id_seq', 12, true);


--
-- Name: upisi_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pguser
--

SELECT pg_catalog.setval('public.upisi_id_seq', 4, true);


--
-- Name: korisnici korisnici_email_key; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.korisnici
    ADD CONSTRAINT korisnici_email_key UNIQUE (email);


--
-- Name: korisnici korisnici_pkey; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.korisnici
    ADD CONSTRAINT korisnici_pkey PRIMARY KEY (id);


--
-- Name: predmeti predmeti_pkey; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.predmeti
    ADD CONSTRAINT predmeti_pkey PRIMARY KEY (id);


--
-- Name: prijave prijave_pkey; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.prijave
    ADD CONSTRAINT prijave_pkey PRIMARY KEY (id);


--
-- Name: prijave unique_korisnik_smjer; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.prijave
    ADD CONSTRAINT unique_korisnik_smjer UNIQUE (korisnik_id, smjer_id);


--
-- Name: upisi upisi_pkey; Type: CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.upisi
    ADD CONSTRAINT upisi_pkey PRIMARY KEY (id);


--
-- Name: korisnici_email_ac117225_like; Type: INDEX; Schema: public; Owner: pguser
--

CREATE INDEX korisnici_email_ac117225_like ON public.korisnici USING btree (email varchar_pattern_ops);


--
-- Name: prijave_korisnik_id_4cd93f5d; Type: INDEX; Schema: public; Owner: pguser
--

CREATE INDEX prijave_korisnik_id_4cd93f5d ON public.prijave USING btree (korisnik_id);


--
-- Name: prijave_smjer_id_3de87c5a; Type: INDEX; Schema: public; Owner: pguser
--

CREATE INDEX prijave_smjer_id_3de87c5a ON public.prijave USING btree (smjer_id);


--
-- Name: upisi_student_id_ea6bf88b; Type: INDEX; Schema: public; Owner: pguser
--

CREATE INDEX upisi_student_id_ea6bf88b ON public.upisi USING btree (student_id);


--
-- Name: upisi_upisnik_id_94fa4fd6; Type: INDEX; Schema: public; Owner: pguser
--

CREATE INDEX upisi_upisnik_id_94fa4fd6 ON public.upisi USING btree (upisnik_id);


--
-- Name: prijave prijave_korisnik_id_4cd93f5d_fk_korisnici_id; Type: FK CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.prijave
    ADD CONSTRAINT prijave_korisnik_id_4cd93f5d_fk_korisnici_id FOREIGN KEY (korisnik_id) REFERENCES public.korisnici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prijave prijave_smjer_id_3de87c5a_fk_smjer_id; Type: FK CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.prijave
    ADD CONSTRAINT prijave_smjer_id_3de87c5a_fk_smjer_id FOREIGN KEY (smjer_id) REFERENCES public.smjerovi(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: upisi upisi_student_id_ea6bf88b_fk_korisnici_id; Type: FK CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.upisi
    ADD CONSTRAINT upisi_student_id_ea6bf88b_fk_korisnici_id FOREIGN KEY (student_id) REFERENCES public.korisnici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: upisi upisi_upisnik_id_94fa4fd6_fk_korisnici_id; Type: FK CONSTRAINT; Schema: public; Owner: pguser
--

ALTER TABLE ONLY public.upisi
    ADD CONSTRAINT upisi_upisnik_id_94fa4fd6_fk_korisnici_id FOREIGN KEY (upisnik_id) REFERENCES public.korisnici(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

