# Generated by Django 5.2.4 on 2025-07-06 17:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0003_rename_name_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(default=datetime.date(2025, 7, 6)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="income",
            name="date",
            field=models.DateTimeField(default="2025-07-06"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="income",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
