# Generated by Django 5.2.4 on 2025-07-08 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_app", "0004_expense_date_expense_updated_at_income_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
