# Generated by Django 5.2.4 on 2025-07-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_alter_category_options_alter_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
